//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastyMod_v2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayerInfiniteHealth {
            get {
                return ((bool)(this["PlayerInfiniteHealth"]));
            }
            set {
                this["PlayerInfiniteHealth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayerInfiniteEnergy {
            get {
                return ((bool)(this["PlayerInfiniteEnergy"]));
            }
            set {
                this["PlayerInfiniteEnergy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayerInfiniteStamina {
            get {
                return ((bool)(this["PlayerInfiniteStamina"]));
            }
            set {
                this["PlayerInfiniteStamina"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayerNeverWanted {
            get {
                return ((bool)(this["PlayerNeverWanted"]));
            }
            set {
                this["PlayerNeverWanted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PlayerMoveSpeedMultiplier {
            get {
                return ((float)(this["PlayerMoveSpeedMultiplier"]));
            }
            set {
                this["PlayerMoveSpeedMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public float PlayerCrouchSpeedMultiplier {
            get {
                return ((float)(this["PlayerCrouchSpeedMultiplier"]));
            }
            set {
                this["PlayerCrouchSpeedMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PlayerJumpMultiplier {
            get {
                return ((float)(this["PlayerJumpMultiplier"]));
            }
            set {
                this["PlayerJumpMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldNpcEsp {
            get {
                return ((bool)(this["WorldNpcEsp"]));
            }
            set {
                this["WorldNpcEsp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldPlayerEsp {
            get {
                return ((bool)(this["WorldPlayerEsp"]));
            }
            set {
                this["WorldPlayerEsp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float WorldEspRange {
            get {
                return ((float)(this["WorldEspRange"]));
            }
            set {
                this["WorldEspRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public string WorldTime {
            get {
                return ((string)(this["WorldTime"]));
            }
            set {
                this["WorldTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WorldTimeScale {
            get {
                return ((float)(this["WorldTimeScale"]));
            }
            set {
                this["WorldTimeScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpawnerSelectedCategory {
            get {
                return ((string)(this["SpawnerSelectedCategory"]));
            }
            set {
                this["SpawnerSelectedCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SpawnerItemAmount {
            get {
                return ((int)(this["SpawnerItemAmount"]));
            }
            set {
                this["SpawnerItemAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscUseStackSize {
            get {
                return ((bool)(this["MiscUseStackSize"]));
            }
            set {
                this["MiscUseStackSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MiscStackSize {
            get {
                return ((int)(this["MiscStackSize"]));
            }
            set {
                this["MiscStackSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscUseDealSuccessChance {
            get {
                return ((bool)(this["MiscUseDealSuccessChance"]));
            }
            set {
                this["MiscUseDealSuccessChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public float MiscDealSuccessChance {
            get {
                return ((float)(this["MiscDealSuccessChance"]));
            }
            set {
                this["MiscDealSuccessChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscUseTrashGrabberCapacity {
            get {
                return ((bool)(this["MiscUseTrashGrabberCapacity"]));
            }
            set {
                this["MiscUseTrashGrabberCapacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int MiscTrashGrabberCapacity {
            get {
                return ((int)(this["MiscTrashGrabberCapacity"]));
            }
            set {
                this["MiscTrashGrabberCapacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscUsePlantGrowSpeedMultiplier {
            get {
                return ((bool)(this["MiscUsePlantGrowSpeedMultiplier"]));
            }
            set {
                this["MiscUsePlantGrowSpeedMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float MiscPlantGrowSpeedMultiplier {
            get {
                return ((float)(this["MiscPlantGrowSpeedMultiplier"]));
            }
            set {
                this["MiscPlantGrowSpeedMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmployeesSelectedProperty {
            get {
                return ((string)(this["EmployeesSelectedProperty"]));
            }
            set {
                this["EmployeesSelectedProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TeleportSelectedCategory {
            get {
                return ((string)(this["TeleportSelectedCategory"]));
            }
            set {
                this["TeleportSelectedCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldFreezeTime {
            get {
                return ((bool)(this["WorldFreezeTime"]));
            }
            set {
                this["WorldFreezeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayerNoClip {
            get {
                return ((bool)(this["PlayerNoClip"]));
            }
            set {
                this["PlayerNoClip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscInstantDeadDrop {
            get {
                return ((bool)(this["MiscInstantDeadDrop"]));
            }
            set {
                this["MiscInstantDeadDrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscInstantLaundering {
            get {
                return ((bool)(this["MiscInstantLaundering"]));
            }
            set {
                this["MiscInstantLaundering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscInstantMixing {
            get {
                return ((bool)(this["MiscInstantMixing"]));
            }
            set {
                this["MiscInstantMixing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1100")]
        public int MenuWidth {
            get {
                return ((int)(this["MenuWidth"]));
            }
            set {
                this["MenuWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("560")]
        public int MenuHeight {
            get {
                return ((int)(this["MenuHeight"]));
            }
            set {
                this["MenuHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1072")]
        public int MenuTabWidth {
            get {
                return ((int)(this["MenuTabWidth"]));
            }
            set {
                this["MenuTabWidth"] = value;
            }
        }
    }
}
